<?php
exit;
//this is just for reference purpose
acf_add_local_field_group([
    'key' => 'group_61681d4e14096',
    'title' => 'Event Bus',
    'fields' => [
        [
            'key' => 'field_61681d5ac63ee',
            'label' => 'Article Lifetime',
            'name' => 'article_lifetime',
            'type' => 'select',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => [
                'width' => '',
                'class' => '',
                'id' => '',
            ],
            'choices' => [
                'evergreen' => 'evergreen',
                'seasonal' => 'seasonal',
                'time-limited' => 'time-limited',
            ],
            'default_value' => false,
            'allow_null' => 0,
            'multiple' => 0,
            'ui' => 0,
            'return_format' => 'value',
            'ajax' => 0,
            'placeholder' => '',
        ],

        [
            'key' => 'field_609a883e62def',
            'label' => 'Hidden Field',
            'name' => 'is_post_new',
            'type' => 'text',
            'instructions' => '(DO NOT USE) This field is used internally by the Bus Plugin.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 'not_new',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ],
    ],
    'location' => [
        [
            [
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'post',
            ],
        ],
    ],
    'menu_order' => 10,
    'position' => 'side',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => [
        0 => 'permalink',
        1 => 'excerpt',
        2 => 'discussion',
        3 => 'comments',
        4 => 'revisions',
        5 => 'slug',
        6 => 'author',
        7 => 'format',
        8 => 'page_attributes',
        9 => 'featured_image',
        10 => 'categories',
        11 => 'tags',
        12 => 'send-trackbacks',
    ],
    'active' => true,
    'description' => '',
]);
